apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-uutarou-pvc
  labels:
    app: wordpress
    role: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: wordpress
      role: database