apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-uutarou-pv
  labels:
    app: wordpress
    role: database
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/uutarou/mysql
    server: kube-master