apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-uutarou-pvc
  labels:
    app: wordpress
    role: web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: wordpress
      role: web