apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-uutarou-pv
  labels:
    app: wordpress
    role: web
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/uutarou/wordpress
    server: kube-master